### ISSUE TITLE
pandoc-citeproc cannot find .bib file 

### ISSUE THREAD

**Issue by pat-s** [hadley/pkgdown#278] opened 2017-03-08 19:07 UTC
```r
pkgdown::build_home()
Building home --------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Updating README.md
Building article 'index.html'
pandoc-citeproc: Could not find vignettes/Biblio.bib
CallStack (from HasCallStack):
  error, called at src/Text/CSL/Pandoc.hs:224:39 in pandoc-citeproc-0.10.4.1-EdjBizYp62fCPHef3CymGR:Text.CSL.Pandoc
pandoc: Error running filter /usr/local/bin/pandoc-citeproc
Filter returned error status 1
Error: pandoc document conversion failed with error 83
```

`README.Rmd` knits without problems. Tried it with "raw.githubuser" path but did not work. Only full local path is working.

**Comment by hadley** [comment] 2017-03-12 20:51
Duplicate of #268

**Closed by hadley** 2017-03-12 20:51 UTC
