### ISSUE TITLE
build_home do not delete correct file with index.Rmd

### ISSUE THREAD

**Issue by cderv** [hadley/pkgdown#266] opened 2017-01-16 19:24 UTC
Hi, 

`build_home` first looks for index.Rmd or README.Rmd, then index.md or README.md. I think it is a great feature to have a README in github different from pkdown home page. 

However, inside the `build_home` function, it do not seems to work equally between `index.Rmd` and `rmarkdown.Rmd`. 

First, when `index.Rmd` is present, `index.md` and `index.html` are rendered. However, contrary to the case with `README.Rmd`, it is not delete because it tries to unlink `README.html`  in both case.  (see under). Same thing, message is not change between index or README.

I think `index.html` sould be deleted as well, as in the *README* case

Moreover, `index.md` is created in the working directory and not deleted but not useful I think. Is it intended ? 

The piece of code I am talking about, used with `README.Rmd` or `index.Rmd`

```r
if (identical(tools::file_ext(data$path), "Rmd")) {
    message("Updating README.md")
    rmarkdown::render(data$path, quiet = TRUE)
    unlink(file.path(pkg$path, "README.html"))
    input <- file.path(path, basename(data$path))
    file.copy(data$path, input)
    on.exit(unlink(input))
    render_rmd(pkg, input, "index.html", depth = depth, 
      data = data, toc = FALSE, strip_header = TRUE)
  }
```

**Comment by hadley** [comment] 2017-03-12 20:37
Duplicate of #235

**Closed by hadley** 2017-03-12 20:37 UTC
