### ISSUE TITLE
Specifying the subsetting function "[.xyz" does not work any more

### ISSUE THREAD

**Issue by jranke** [hadley/pkgdown#335] opened 2017-05-05 11:06 UTC
With previous versions of pkgdown, I could have

    - "[.mmkin"

in my _pkgdown.yml file. However, with current pkgdown I get

    Building function reference ---------------------------------------------------
    Fehler: Failed to parse: `[.mmkin` in `_pkgdown.yml`
    <text>:1:1: Unerwartete(s) '['
    1: [
        ^

I get the same error if I use

    - "\u005B.mmkin"

i.e. the unicode is correctly interpreted to an opening square bracket, so I get the same error message.

**Comment by hadley** [comment] 2017-05-05 12:42
Duplicate of #309

**Closed by hadley** 2017-05-05 12:42 UTC
