### ISSUE TITLE
Missing documentation when using dummy function to document s4 methods

### ISSUE THREAD

**Issue by GShotwell** [hadley/pkgdown#395] opened 2017-08-21 15:07 UTC
We have a few s4 methods which we document with a dummy function. We document a null value and give that function a name, and then use `@rdname` on the actual methods. However, when I build the site the links to the methods are not showing up in the function reference, and instead I just see the title of the dummy function:

<img width="785" alt="screen shot 2017-08-21 at 12 07 16 pm" src="https://user-images.githubusercontent.com/8417172/29525520-56410da0-8669-11e7-8644-6fdacfdbd159.png">

The code which is generating the problem is here: https://github.com/Crunch-io/rcrunch/blob/b16ae1346a7239c9067dedaf56be6702f33ef5ee/R/dataset-catalog.R#L66-L91

It seems like packagedown is building the documentation properly for some other functions with this pattern. So maybe it has something to do with the fact that these methods are for `[[`?

**Comment by jennybc** [comment] 2017-08-21 15:49
Probably duplicate of or related to #373

**Closed** 2017-08-22 15:11 UTC
